### ISSUE TITLE
pupa conversion

### ISSUE THREAD

**Issue by jamesturk** [openstates/openstates#1442]
Our big push for this year is to modernize our infrastructure.  The best way to help with that is to grab a state and port its scrapers from Billy to Pupa. All contributions are extremely welcome, and this is a great way to get to know the OS scrapers!

Here's documentation on the process: http://docs.openstates.org/en/latest/contributing/pupa-conversion.html
- [x] New Hampshire - #1551 - Tim WIP
- [x] Illinois - #1386* - Forest WIP
- [x] Texas - #1526*
- [x] New York - #1664
- [x] Massachusetts - [WIP Branch](https://github.com/openstates/openstates/tree/pupa-ma) - James working on 
- [x] Puerto Rico - #1730 - James reviewing
- [x] Louisiana - #1606 - James reviewing
- [x] West Virginia - #1556* - James reviewing
- [x] California - #1648 - working on eval/fixes
- [x] Iowa - #1604 - James
- [x] Colorado - #1616 - James
- [x] Oklahoma - #1726 - resolving SSL issues & evaluating
- [x] Georgia - #1722 
- [x] Nevada - #1710
- [x] Alaska - #1708
- [x] Rhode Island - #1557*
- [x] Tennessee - #1543
- [x] North Dakota - #1725
- [x] Utah - #1724
- [x] Maryland - [WIP Branch](https://github.com/openstates/openstates/tree/pupa-md) , #1712
- [x] Washington - #1647 
- [x] Maine - #1558*
- [x] Mississippi - #1655
- [x] Alabama
- [x] Arizona
- [x] Arkansas
- [x] Connecticut
- [x] Delaware
- [x] District of Columbia
- [x] Florida
- [x] Hawaii
- [x] Idaho
- [x] Indiana
- [x] Kansas
- [x] Kentucky
- [x] Michigan
- [x] Minnesota
- [x] Missouri
- [x] Montana
- [x] Nebraska
- [x] New Jersey
- [x] New Mexico
- [x] North Carolina
- [x] Ohio
- [x] Oregon
- [x] Pennsylvania
- [x] South Carolina
- [x] South Dakota
- [x] Vermont
- [x] Virginia
- [x] Wisconsin
- [x] Wyoming

_Asterisks indicate incomplete PRs that haven't been updated in a while, and might be closed going forward._

**Comment by mroswell** [comment]
I'll work on Maryland. (Happy to partner with any other Marylanders as well.)

**Comment by showerst** [comment]
I'll take a shot at New Hampshire.

**Comment by jamesturk** [comment]
Going to take on Montana as my next one as I test my own documentation

**Comment by jamesthechamp** [comment]
i am gonna start work for Idaho...

**Comment by jamesturk** [comment]
I'll take a pass at Massachusetts, maybe even get a working vote scraper in there

**Comment by In-vincible** [comment]
I want to start work on Arkansas, I have already started my work.

**Comment by cliftonmcintosh** [comment]
#1500 is the start of converting New Mexico.

**Comment by giantryansaul** [comment]
I'm looking into Oregon at the moment.

**Comment by hiteshgarg14** [comment]
I will take a shot at Delaware.

**Comment by mileswwatkins** [comment]
Vermont!

**Comment by carlvlewis** [comment]
Me and the [Open Savannah](http://github.com/opensavannah) brigade will pick up Ga.

**Comment by gregoryfoster** [comment]
#1526 is a beginning for the TX scrapers.

A group of interested folks at [Open Austin](https://github.com/open-austin/project-ideas/issues/92) have begun learning more about Open States.  Thank you so much for picking up this project from Sunlight Foundation and making it even better.

**Comment by In-vincible** [comment]
I will take up Ohio, since AR, work is almost complete.

**Comment by mshenfield** [comment]
Going to tackle Tennessee

**Comment by hiteshgarg14** [comment]
Arizona!

**Comment by jmcarp** [comment]
I'll look at PA tonight.

**Comment by jamesthechamp** [comment]
i gonna take a look at hawaii...

**Comment by brymut** [comment]
Going to check out Georgia. :)

**Comment by amitnagis** [comment]
I am going to take a look at Alaska

**Comment by lmdragun** [comment]
I'm going to look at Maine

**Comment by jalbertbowden** [comment]
i'm going to do dc

**Comment by jschiarizzi** [comment]
I'm working on Utah!

**Comment by gregjd** [comment]
I'm working on Rhode Island!

**Comment by hmoco** [comment]
I've answered Kentucky's calling

**Comment by gregjd** [comment]
@carlvlewis @brymut — FYI, you both put Georgia

**Comment by gregjd** [comment]
I'll take North Dakota

**Comment by brymut** [comment]
Thanks @gregjd, didn't notice that @carlvlewis, sorry.

I'll be moving on to South Carolina.

**Comment by carlvlewis** [comment]
Oh, well, oops. I can do it or he can. No big to me.

**Comment by In-vincible** [comment]
@jamesturk I have created another PR #1574 for ar conversion, I have closed old PR(#1503) it's all done with one doubt.

**Comment by jamesthechamp** [comment]
next nevada....

**Comment by In-vincible** [comment]
Colorado started :)

**Comment by hiteshgarg14** [comment]
Connecticut!

**Comment by mbacchi** [comment]
Going to try NY, first time contributor here but want to get involved.

**Comment by frenata** [comment]
I'm starting work on Iowa

**Comment by cliftonmcintosh** [comment]
@jamesturk  and @mileswwatkins 

#1520 is ready for your review.

**Comment by leslie-huang** [comment]
I'll take Louisiana!

**Comment by giantryansaul** [comment]
@jamesturk and @mileswwatkins OR is ready for review as well.

**Comment by brymut** [comment]
Hi @mroswell, on the pupa conversion status in the meta repo, it mentions that I have also claimed Georgia along with @carlvlewis. However, I did take note of that a while ago and claimed SCarolina and completed a pull request #1569 . Could you please reflect this on the pupa conversion status table?

**Comment by mileswwatkins** [comment]
@brymut, thanks for the PR! The official source of truth for Pupa conversion status is this ticket, so we're all good.

**Comment by brymut** [comment]
Alright, thanks @mileswwatkins :+1:

**Comment by In-vincible** [comment]
I will take up Louisiana.

**Comment by In-vincible** [comment]
South Dakota

**Comment by hiteshgarg14** [comment]
Iowa

**Comment by jamesturk** [comment]
@hiteshgarg14 Iowa is in progress here: https://github.com/openstates/openstates/pull/1604 

be sure to check the PRs :) I'll be working to update the list

**Comment by hiteshgarg14** [comment]
Thanks @jamesturk 
I will be working on Washington now :smiley:

**Comment by In-vincible** [comment]
North Dakota

**Comment by gregjd** [comment]
@In-vincible Whoops, I had also claimed North Dakota above. Have you done any work on it? I did the conversion of `legislators.py`. (Didn't commit it to my branch/open a PR because I already have an open PR for Rhode Island my North Dakota work is on the same branch, so this would show up in Rhode Island's PR if I did that. What I should do is finish RI so that it can be accepted and then I won't have this problem anymore....)

**Comment by In-vincible** [comment]
@gregjd no issues, thanks for informing me on this one,I failed to check all the comments above :sweat_smile: , I was also on legislators conversion ;)

**Comment by In-vincible** [comment]
I will take up Georgia tomorrow, please inform me if someone's already working.

**Comment by scichelli** [comment]
@jamesturk I've talked with @gregoryfoster about picking up his work-in-progress on the TX conversion, probably working off my own fork. I'm still reading the how-to-convert docs at the moment, but I have the `billy` tx scraper running locally. :)

**Comment by hiteshgarg14** [comment]
@jschiarizzi  do you want to free `Utah` up or do you think you'll get back to it?

**Comment by hiteshgarg14** [comment]
North Dakota!

**Comment by jamesturk** [comment]
🎉 🎉 done🎉 🎉 

thanks everyone for all the amazing effort put in to get this done over the past three months!
